articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.article_list, name="list"),
    path('<slug:slug>', views.article_detail, name="detail"),
    path('search/', views.articles_search, name="search")
    
]

musicblog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf.urls.static import static 
from django.conf import settings
from multiurl import multiurl
 

 #when the url is about/ call views.about function
 #when you django goes to articles/ it gets sent to the articles url.py file
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("articles.urls")),
    path('about/', views.about, name="about"),
    path('contact/', views.contact, name="contact")
    
]

urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from django.db import models

# Create your models here.

class Article(models.Model):
	title = models.CharField(max_length =100) 
	slug = models.SlugField()
	quote = models.CharField(max_length=200)
	artist = models.CharField(default='Unknown', max_length=200)
	producer = models.CharField(default='Unknown', max_length=200)
	genre = models.CharField(default=None, blank=True, null=True, max_length=200)
	vocals_body = models.TextField(default=None, blank=True, null=True)
	beat_body = models.TextField(default=None, blank=True, null=True)
	date = models.DateTimeField(auto_now_add=True)
	album_art = models.ImageField(default='default.png', blank=True)
	artist_image = models.ImageField(default=None, blank=True, null=True)
	embed = models.TextField(default=None, blank=True, null=True)
	author = models.CharField(default='Unknown', max_length=200)
	#add in author later
	
	def __str__(self):
		return self.title;

	def snippet(self):
		if (len(self.vocals_body) <= 400):
			return self.vocals_body
		else:
			return self.vocals_body[:400] + '...'

	
	
		
		

searchbar/models.py
from django.db import models

# Create your models here.

searchbar/forms.py
from django import forms
from articles import models

class SearchForm(forms.ModelForm):
	# for styling - removes label and add placeholder
	title = forms.CharField(label='', widget=forms.TextInput(attrs={'placeholder': 'Search'}))
	# model form set up with only title field
	class Meta:
		model = models.Article
		fields = ['title'] 

articles/views.py
from django.shortcuts import render
from .models import Article
from django.http import HttpResponse
from searchbar import forms
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# Create your views here.

#when views.article_list is called in url file this function is called
#render the html template

def article_list(request):
	# all the articles stored
	articles_list = Article.objects.all().order_by('-date')
	page = request.GET.get('page', 1)

	paginator = Paginator(articles_list, 4)
	try: 
		articles = paginator.page(page)
	except PageNotAnInteger:
		articles = paginator.page(1)
	except EmptyPage:
		articles = paginator.page(paginator.num_pages)

	return render(request, 'articles/article_list.html', {"articles": articles})

def article_detail(request, slug):
	# get the individual blog post where the slug equals the slug of the article
	# clicked on
	article = Article.objects.get(slug=slug)
	return render(request, 'articles/article_detail.html', {'article':article})

def articles_search(request):
	if request.method == 'GET':
		form = forms.SearchForm(request.GET, request.FILES)
		
		if form.is_valid() or not form.is_valid():
			# this is the text typed into the search bar
			search_word = form.cleaned_data['title']
			# only get articles with titles that contain search word
			filtered_articles = Article.objects.filter(title__icontains=search_word)
			# if nothing matches your search display message
			if(filtered_articles):
				not_found =''
			else:
				not_found = "Sorry, no songs with that name have been posted."

			page = request.GET.get('page', 1)

			paginator = Paginator(filtered_articles, 50)
			try: 
				articles = paginator.page(page)
			except PageNotAnInteger:
				articles = paginator.page(1)
			except EmptyPage:
				articles = paginator.page(paginator.num_pages)
			# return all needed information to article_search page	
			return render(request, 'articles/article_search.html', {"articles": articles,
				"search_word":search_word, "not_found": not_found})

musicblog/views.py
from django.http import HttpResponse
from django.shortcuts import render
from articles import models



def home(request):
	#return HttpResponse("homepage")
	return render(request, "home.html")

def about(request):
	#return HttpResponse("about")
	return render(request, "about.html")

def contact(request):
	#return HttpResponse("about")
	return render(request, "contact.html")

searchbar/views.py
from django.shortcuts import render

# Create your views here.

articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}

<div class="article-detail">
	<div class="detail-article">
		
		<section class="detail-title">
			<h2>{{ article.title }}</h2>
			<p>{{ article.quote}}</p>

		</section>

		<section class="detail-album-art">
		<img src="{{article.album_art.url }}" style="max-width: 600px; max-height: 600px; width: 100%">
		</section>

		<section class="detail-info-1">
			<p> Genre: {{ article.genre }} </p>
			<p>{{ article.vocals_body }}</p>
		</section>

		<section class="detail-album-art">
		<img src="{{article.artist_image.url }}" style="max-width: 600px; max-height: 600px; width: 100%">
		</section>

		<section class="detail-info-2">
			<p>{{ article.beat_body }}</p>
		</section>

		<section class="detail-embed">
			<p> {{ article.embed | safe}} </p>
		</section>

		<section class="detail-author-date">
			<p>Published by: {{ article.author}} &nbsp;&nbsp;-&nbsp;&nbsp; {{ article.date }}</p>
		</section>

		
	</div>
</div>

{% endblock %}

articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}


{% block content %}
		{% for article in articles %}
		<div class="list-article">
			
			<section class="list-album-art">
				<a href="{% url 'articles:detail' slug=article.slug %}">
				<img src="{{article.album_art.url }}" style="max-width: 600px; max-height: 600px; width: 100%">
				</a>
			</section>
			<h2><a href="{% url 'articles:detail' slug=article.slug %}">{{ article.title }}</a></h2>
			<p>{{ article.snippet }}</p>
			<p>{{ article.date }}</p>
		</div>
		{% endfor %}
	</div>

	{% if articles.has_other_pages %}
  <center>
  <ul class="pagination">
    {% if articles.has_previous %}
      <li><a href="?page={{ articles.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in articles.paginator.page_range %}
      {% if articles.number == i %}
        <li class="active"><span>{{ i }}</span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if articles.has_next %}
      <li><a href="?page={{ articles.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}
</center>

{% endblock %}

articles/templates/articles/article_search.html
{% extends 'base_layout.html' %}


{% block content %}
	<div class="search-article">
	<h1> You searched for: {{ search_word }} </h1>
	<h1> {{ not_found }}</h1>
	<div class="articles">
		{% for article in articles %}
		<div class="article">
			<h2><a href="{% url 'articles:detail' slug=article.slug %}">{{ article.title }}</a></h2>
			<p>{{ article.snippet }}</p>
			<p>{{ article.date }}</p>
		</div>
		{% endfor %}
	</div>
	</div>

	
{% endblock %}

templates/about.html
{% extends 'base_layout.html' %}

{% block content %}

<section class="contact">
	<h1>About</h1>
	<p>Recognition Magazine is dedicated to bringing artists who are making unique and high quality music into the spotlight. We are always looking for new and upcoming artists to feature on our site. To submit music to be highlighted in Recognition Magazine see our <a href="{% url 'contact' %}">contact</a> page.</p>
	<br> <br> <br> <br>
</section>
{% endblock %}

templates/base_layout.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>
<head>
	<title>Article</title>

	<link rel="stylesheet" href ="{% static 'styles.css' %}">
	<link href="https://fonts.googleapis.com/css?family=Roboto:700i" rel="stylesheet">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	<div class="container" style="margin-left:2%; margin-right:2%; margin-top: 2%;">
		
		<nav>
			
			<a href = "{% url 'articles:list' %}">
				<img class = "logo" src="{% static 'Recognition-logo.png' %}">
				<h1 style="visibility: hidden; position: absolute;">
					Recognition Magazine
				</h1>
			</a>
			<ul>
				<li><a href = "{% url 'articles:list' %}">HOME</a></li>
				<li><a href = "{% url 'contact' %}">CONTACT</a></li>
				<li><a href = "{% url 'about' %}">ABOUT</a></li>
				<li></li>
			</ul>
			
		</nav>
		<form class="search-form" action="{% url 'articles:search' %}" method="get">
				{% csrf_token %}
				{{ search_form }}			
			</form>


		<article>
			{% block content %}
			{% endblock %}
		</article>
	</div>
	<section class="footer">
		<p>&copy; 2018 Recognition Magazine</p> 
	</section>
</body>
</html>

templates/contact.html
{% extends 'base_layout.html' %}

{% block content %}

<section class="contact">
	<h1>Contact</h1>
	<p>To contact us to submit music or with any other inquiry, please email: northcoastrecords.management@gmail.com</p>
	<br> <br> <br> <br>
</section>
{% endblock %}